// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0--rc2
// source: protos/account.proto

package account

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomType int32

const (
	// todo 类型待定
	CustomType_Normal     CustomType = 0 // 普通客户
	CustomType_Enterprise CustomType = 1 // 企业客户
)

// Enum value maps for CustomType.
var (
	CustomType_name = map[int32]string{
		0: "Normal",
		1: "Enterprise",
	}
	CustomType_value = map[string]int32{
		"Normal":     0,
		"Enterprise": 1,
	}
)

func (x CustomType) Enum() *CustomType {
	p := new(CustomType)
	*p = x
	return p
}

func (x CustomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_account_proto_enumTypes[0].Descriptor()
}

func (CustomType) Type() protoreflect.EnumType {
	return &file_protos_account_proto_enumTypes[0]
}

func (x CustomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomType.Descriptor instead.
func (CustomType) EnumDescriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{0}
}

type CustomIDType int32

const (
	// todo 其他证件类型待定
	CustomIDType_IdentityCard CustomIDType = 0 // 中华人民共和国居民身份证
)

// Enum value maps for CustomIDType.
var (
	CustomIDType_name = map[int32]string{
		0: "IdentityCard",
	}
	CustomIDType_value = map[string]int32{
		"IdentityCard": 0,
	}
)

func (x CustomIDType) Enum() *CustomIDType {
	p := new(CustomIDType)
	*p = x
	return p
}

func (x CustomIDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomIDType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_account_proto_enumTypes[1].Descriptor()
}

func (CustomIDType) Type() protoreflect.EnumType {
	return &file_protos_account_proto_enumTypes[1]
}

func (x CustomIDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomIDType.Descriptor instead.
func (CustomIDType) EnumDescriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{1}
}

type RiskLevel int32

const (
	RiskLevel_WeakLevel   RiskLevel = 0 // 低风险
	RiskLevel_MiddleLevel RiskLevel = 1 // 中风险
	RiskLevel_HighLevel   RiskLevel = 2 // 高风险
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "WeakLevel",
		1: "MiddleLevel",
		2: "HighLevel",
	}
	RiskLevel_value = map[string]int32{
		"WeakLevel":   0,
		"MiddleLevel": 1,
		"HighLevel":   2,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_account_proto_enumTypes[2].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_protos_account_proto_enumTypes[2]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{2}
}

type BankCardType int32

const (
	// 参考缩写：https://help.epay.163.com/platform/question.html?quesId=2017010218HQ00000076
	BankCardType_AbcDebitQuickPay  BankCardType = 0 // 农业银行
	BankCardType_IcbcDebitQuickPay BankCardType = 1 // 工商银行
)

// Enum value maps for BankCardType.
var (
	BankCardType_name = map[int32]string{
		0: "AbcDebitQuickPay",
		1: "IcbcDebitQuickPay",
	}
	BankCardType_value = map[string]int32{
		"AbcDebitQuickPay":  0,
		"IcbcDebitQuickPay": 1,
	}
)

func (x BankCardType) Enum() *BankCardType {
	p := new(BankCardType)
	*p = x
	return p
}

func (x BankCardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankCardType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_account_proto_enumTypes[3].Descriptor()
}

func (BankCardType) Type() protoreflect.EnumType {
	return &file_protos_account_proto_enumTypes[3]
}

func (x BankCardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankCardType.Descriptor instead.
func (BankCardType) EnumDescriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{3}
}

type GetCustomInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdCard string       `protobuf:"bytes,1,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	IdType CustomIDType `protobuf:"varint,2,opt,name=id_type,json=idType,proto3,enum=account.CustomIDType" json:"id_type,omitempty"`
}

func (x *GetCustomInfoRequest) Reset() {
	*x = GetCustomInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomInfoRequest) ProtoMessage() {}

func (x *GetCustomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCustomInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomInfoRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *GetCustomInfoRequest) GetIdType() CustomIDType {
	if x != nil {
		return x.IdType
	}
	return CustomIDType_IdentityCard
}

type GetCustomInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetCustomInfoData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCustomInfoResponse) Reset() {
	*x = GetCustomInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomInfoResponse) ProtoMessage() {}

func (x *GetCustomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCustomInfoResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomInfoResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCustomInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCustomInfoResponse) GetData() *GetCustomInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCustomInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // 客户id
	Name                string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                               // 客户名称
	Type                CustomType      `protobuf:"varint,3,opt,name=type,proto3,enum=account.CustomType" json:"type,omitempty"`                                      // 客户类型
	IdType              CustomIDType    `protobuf:"varint,4,opt,name=id_type,json=idType,proto3,enum=account.CustomIDType" json:"id_type,omitempty"`                  // 客户证件类型
	IdCard              string          `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`                                             // 客户证件号码
	IdCardValidityStart int64           `protobuf:"varint,6,opt,name=id_card_validity_start,json=idCardValidityStart,proto3" json:"id_card_validity_start,omitempty"` // 客户证件有效期开始时间，毫秒时间戳
	IdCardValidityEnd   int64           `protobuf:"varint,7,opt,name=id_card_validity_end,json=idCardValidityEnd,proto3" json:"id_card_validity_end,omitempty"`       // 客户证件有效期结束时间，毫秒时间戳
	PhoneNumber         string          `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                              // 客户手机号
	Gender              bool            `protobuf:"varint,9,opt,name=gender,proto3" json:"gender,omitempty"`                                                          // 客户性别，true 为男性，false 为女性
	IsMarried           bool            `protobuf:"varint,10,opt,name=is_married,json=isMarried,proto3" json:"is_married,omitempty"`                                  // 客户是否已婚
	CreatedDate         int64           `protobuf:"varint,11,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`                            // 客户开户日期，毫秒时间戳
	RiskLevel           RiskLevel       `protobuf:"varint,12,opt,name=risk_level,json=riskLevel,proto3,enum=account.RiskLevel" json:"risk_level,omitempty"`           // 客户风控承担等级
	RiskValidityEnd     int64           `protobuf:"varint,13,opt,name=risk_validity_end,json=riskValidityEnd,proto3" json:"risk_validity_end,omitempty"`              // 客户风控承担等级有效期结束时间，毫秒时间戳
	BankCards           []*BankCardInfo `protobuf:"bytes,14,rep,name=bank_cards,json=bankCards,proto3" json:"bank_cards,omitempty"`                                   // 客户银行卡信息
}

func (x *GetCustomInfoData) Reset() {
	*x = GetCustomInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomInfoData) ProtoMessage() {}

func (x *GetCustomInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomInfoData.ProtoReflect.Descriptor instead.
func (*GetCustomInfoData) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomInfoData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCustomInfoData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCustomInfoData) GetType() CustomType {
	if x != nil {
		return x.Type
	}
	return CustomType_Normal
}

func (x *GetCustomInfoData) GetIdType() CustomIDType {
	if x != nil {
		return x.IdType
	}
	return CustomIDType_IdentityCard
}

func (x *GetCustomInfoData) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *GetCustomInfoData) GetIdCardValidityStart() int64 {
	if x != nil {
		return x.IdCardValidityStart
	}
	return 0
}

func (x *GetCustomInfoData) GetIdCardValidityEnd() int64 {
	if x != nil {
		return x.IdCardValidityEnd
	}
	return 0
}

func (x *GetCustomInfoData) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetCustomInfoData) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *GetCustomInfoData) GetIsMarried() bool {
	if x != nil {
		return x.IsMarried
	}
	return false
}

func (x *GetCustomInfoData) GetCreatedDate() int64 {
	if x != nil {
		return x.CreatedDate
	}
	return 0
}

func (x *GetCustomInfoData) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_WeakLevel
}

func (x *GetCustomInfoData) GetRiskValidityEnd() int64 {
	if x != nil {
		return x.RiskValidityEnd
	}
	return 0
}

func (x *GetCustomInfoData) GetBankCards() []*BankCardInfo {
	if x != nil {
		return x.BankCards
	}
	return nil
}

type BankCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankCardType   BankCardType `protobuf:"varint,1,opt,name=bank_card_type,json=bankCardType,proto3,enum=account.BankCardType" json:"bank_card_type,omitempty"` // 银行卡类型
	BankCardNumber string       `protobuf:"bytes,2,opt,name=bank_card_number,json=bankCardNumber,proto3" json:"bank_card_number,omitempty"`                      // 银行卡号
}

func (x *BankCardInfo) Reset() {
	*x = BankCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardInfo) ProtoMessage() {}

func (x *BankCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardInfo.ProtoReflect.Descriptor instead.
func (*BankCardInfo) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{3}
}

func (x *BankCardInfo) GetBankCardType() BankCardType {
	if x != nil {
		return x.BankCardType
	}
	return BankCardType_AbcDebitQuickPay
}

func (x *BankCardInfo) GetBankCardNumber() string {
	if x != nil {
		return x.BankCardNumber
	}
	return ""
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{4}
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateCustomInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCustomInfoRequest) Reset() {
	*x = UpdateCustomInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCustomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomInfoRequest) ProtoMessage() {}

func (x *UpdateCustomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{6}
}

type UpdateCustomInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateCustomInfoResponse) Reset() {
	*x = UpdateCustomInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCustomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomInfoResponse) ProtoMessage() {}

func (x *UpdateCustomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomInfoResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCustomInfoResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCustomInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PullBackCustomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullBackCustomRequest) Reset() {
	*x = PullBackCustomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullBackCustomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullBackCustomRequest) ProtoMessage() {}

func (x *PullBackCustomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullBackCustomRequest.ProtoReflect.Descriptor instead.
func (*PullBackCustomRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{8}
}

type PullBackCustomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PullBackCustomResponse) Reset() {
	*x = PullBackCustomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullBackCustomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullBackCustomResponse) ProtoMessage() {}

func (x *PullBackCustomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullBackCustomResponse.ProtoReflect.Descriptor instead.
func (*PullBackCustomResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{9}
}

func (x *PullBackCustomResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PullBackCustomResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SetRiskSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRiskSetRequest) Reset() {
	*x = SetRiskSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRiskSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRiskSetRequest) ProtoMessage() {}

func (x *SetRiskSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRiskSetRequest.ProtoReflect.Descriptor instead.
func (*SetRiskSetRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{10}
}

type SetRiskSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetRiskSetResponse) Reset() {
	*x = SetRiskSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRiskSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRiskSetResponse) ProtoMessage() {}

func (x *SetRiskSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRiskSetResponse.ProtoReflect.Descriptor instead.
func (*SetRiskSetResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{11}
}

func (x *SetRiskSetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetRiskSetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetRiskSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRiskSetRequest) Reset() {
	*x = GetRiskSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRiskSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskSetRequest) ProtoMessage() {}

func (x *GetRiskSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskSetRequest.ProtoReflect.Descriptor instead.
func (*GetRiskSetRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{12}
}

type GetRiskSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetRiskSetResponse) Reset() {
	*x = GetRiskSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRiskSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskSetResponse) ProtoMessage() {}

func (x *GetRiskSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskSetResponse.ProtoReflect.Descriptor instead.
func (*GetRiskSetResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{13}
}

func (x *GetRiskSetResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRiskSetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SubmitAnswersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubmitAnswersRequest) Reset() {
	*x = SubmitAnswersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswersRequest) ProtoMessage() {}

func (x *SubmitAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswersRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswersRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{14}
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitAnswerResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubmitAnswerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetBankBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBankBalanceRequest) Reset() {
	*x = GetBankBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBankBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankBalanceRequest) ProtoMessage() {}

func (x *GetBankBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBankBalanceRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{16}
}

type GetBankBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetBankBalanceResponse) Reset() {
	*x = GetBankBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBankBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankBalanceResponse) ProtoMessage() {}

func (x *GetBankBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBankBalanceResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{17}
}

func (x *GetBankBalanceResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetBankBalanceResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BindBankCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BindBankCardRequest) Reset() {
	*x = BindBankCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindBankCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindBankCardRequest) ProtoMessage() {}

func (x *BindBankCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindBankCardRequest.ProtoReflect.Descriptor instead.
func (*BindBankCardRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{18}
}

type BindBankCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BindBankCardResponse) Reset() {
	*x = BindBankCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindBankCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindBankCardResponse) ProtoMessage() {}

func (x *BindBankCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindBankCardResponse.ProtoReflect.Descriptor instead.
func (*BindBankCardResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{19}
}

func (x *BindBankCardResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BindBankCardResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnbindBankCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnbindBankCardRequest) Reset() {
	*x = UnbindBankCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbindBankCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindBankCardRequest) ProtoMessage() {}

func (x *UnbindBankCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindBankCardRequest.ProtoReflect.Descriptor instead.
func (*UnbindBankCardRequest) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{20}
}

type UnbindBankCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UnbindBankCardResponse) Reset() {
	*x = UnbindBankCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_account_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbindBankCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindBankCardResponse) ProtoMessage() {}

func (x *UnbindBankCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_account_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindBankCardResponse.ProtoReflect.Descriptor instead.
func (*UnbindBankCardResponse) Descriptor() ([]byte, []int) {
	return file_protos_account_proto_rawDescGZIP(), []int{21}
}

func (x *UnbindBankCardResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnbindBankCardResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protos_account_proto protoreflect.FileDescriptor

var file_protos_account_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x2e,
	0x0a, 0x07, 0x69, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x49, 0x44, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x69, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6d,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2e, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa1, 0x04,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x2e, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x49, 0x44, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x69, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x16, 0x69, 0x64, 0x5f,
	0x63, 0x61, 0x72, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x69, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2f,
	0x0a, 0x14, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x69, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x45, 0x6e, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x5f, 0x6d, 0x61, 0x72, 0x72, 0x69, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x4d, 0x61, 0x72, 0x72, 0x69, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x0a,
	0x72, 0x69, 0x73, 0x6b, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x69, 0x73, 0x6b, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x2a, 0x0a, 0x11, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x5f, 0x65, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x69, 0x73, 0x6b,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x45, 0x6e, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x62,
	0x61, 0x6e, 0x6b, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61,
	0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x22, 0x75, 0x0a, 0x0c, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x3b, 0x0a, 0x0e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0c, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x10, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x61,
	0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x3d, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x17, 0x0a, 0x15,
	0x50, 0x75, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x16, 0x50, 0x75, 0x6c, 0x6c, 0x42, 0x61, 0x63,
	0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x52, 0x69, 0x73, 0x6b,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x69, 0x73,
	0x6b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x3c, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x17, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e,
	0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x42, 0x69, 0x6e, 0x64, 0x42, 0x61,
	0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a,
	0x14, 0x42, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x17, 0x0a, 0x15, 0x55,
	0x6e, 0x62, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x16, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x42, 0x61,
	0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x2a, 0x28, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x10, 0x01, 0x2a, 0x20,
	0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x44, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x10, 0x00,
	0x2a, 0x3a, 0x0a, 0x09, 0x52, 0x69, 0x73, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0d, 0x0a,
	0x09, 0x57, 0x65, 0x61, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x48, 0x69, 0x67, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x10, 0x02, 0x2a, 0x3b, 0x0a, 0x0c,
	0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x41, 0x62, 0x63, 0x44, 0x65, 0x62, 0x69, 0x74, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x50, 0x61, 0x79,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x63, 0x62, 0x63, 0x44, 0x65, 0x62, 0x69, 0x74, 0x51,
	0x75, 0x69, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x10, 0x01, 0x32, 0xfe, 0x02, 0x0a, 0x0e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x50, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x50, 0x75, 0x6c, 0x6c, 0x42, 0x61, 0x63,
	0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xf3, 0x01, 0x0a, 0x0e, 0x52,
	0x69, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a,
	0x0a, 0x53, 0x65, 0x74, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x69, 0x73,
	0x6b, 0x53, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x69,
	0x73, 0x6b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73,
	0x12, 0x1d, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x32, 0x8a, 0x02, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x42, 0x69, 0x6e,
	0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x55, 0x6e, 0x62, 0x69,
	0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x6b, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x0a,
	0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x75, 0x6e, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x01, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_account_proto_rawDescOnce sync.Once
	file_protos_account_proto_rawDescData = file_protos_account_proto_rawDesc
)

func file_protos_account_proto_rawDescGZIP() []byte {
	file_protos_account_proto_rawDescOnce.Do(func() {
		file_protos_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_account_proto_rawDescData)
	})
	return file_protos_account_proto_rawDescData
}

var file_protos_account_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_protos_account_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_protos_account_proto_goTypes = []interface{}{
	(CustomType)(0),                  // 0: account.CustomType
	(CustomIDType)(0),                // 1: account.CustomIDType
	(RiskLevel)(0),                   // 2: account.RiskLevel
	(BankCardType)(0),                // 3: account.BankCardType
	(*GetCustomInfoRequest)(nil),     // 4: account.GetCustomInfoRequest
	(*GetCustomInfoResponse)(nil),    // 5: account.GetCustomInfoResponse
	(*GetCustomInfoData)(nil),        // 6: account.GetCustomInfoData
	(*BankCardInfo)(nil),             // 7: account.BankCardInfo
	(*CreateAccountRequest)(nil),     // 8: account.CreateAccountRequest
	(*CreateAccountResponse)(nil),    // 9: account.CreateAccountResponse
	(*UpdateCustomInfoRequest)(nil),  // 10: account.UpdateCustomInfoRequest
	(*UpdateCustomInfoResponse)(nil), // 11: account.UpdateCustomInfoResponse
	(*PullBackCustomRequest)(nil),    // 12: account.PullBackCustomRequest
	(*PullBackCustomResponse)(nil),   // 13: account.PullBackCustomResponse
	(*SetRiskSetRequest)(nil),        // 14: account.SetRiskSetRequest
	(*SetRiskSetResponse)(nil),       // 15: account.SetRiskSetResponse
	(*GetRiskSetRequest)(nil),        // 16: account.GetRiskSetRequest
	(*GetRiskSetResponse)(nil),       // 17: account.GetRiskSetResponse
	(*SubmitAnswersRequest)(nil),     // 18: account.SubmitAnswersRequest
	(*SubmitAnswerResponse)(nil),     // 19: account.SubmitAnswerResponse
	(*GetBankBalanceRequest)(nil),    // 20: account.GetBankBalanceRequest
	(*GetBankBalanceResponse)(nil),   // 21: account.GetBankBalanceResponse
	(*BindBankCardRequest)(nil),      // 22: account.BindBankCardRequest
	(*BindBankCardResponse)(nil),     // 23: account.BindBankCardResponse
	(*UnbindBankCardRequest)(nil),    // 24: account.UnbindBankCardRequest
	(*UnbindBankCardResponse)(nil),   // 25: account.UnbindBankCardResponse
}
var file_protos_account_proto_depIdxs = []int32{
	1,  // 0: account.GetCustomInfoRequest.id_type:type_name -> account.CustomIDType
	6,  // 1: account.GetCustomInfoResponse.data:type_name -> account.GetCustomInfoData
	0,  // 2: account.GetCustomInfoData.type:type_name -> account.CustomType
	1,  // 3: account.GetCustomInfoData.id_type:type_name -> account.CustomIDType
	2,  // 4: account.GetCustomInfoData.risk_level:type_name -> account.RiskLevel
	7,  // 5: account.GetCustomInfoData.bank_cards:type_name -> account.BankCardInfo
	3,  // 6: account.BankCardInfo.bank_card_type:type_name -> account.BankCardType
	4,  // 7: account.AccountService.GetCustomInfo:input_type -> account.GetCustomInfoRequest
	8,  // 8: account.AccountService.CreateAccount:input_type -> account.CreateAccountRequest
	10, // 9: account.AccountService.UpdateCustomInfo:input_type -> account.UpdateCustomInfoRequest
	12, // 10: account.AccountService.PullBackCustom:input_type -> account.PullBackCustomRequest
	14, // 11: account.RiskSetService.SetRiskSet:input_type -> account.SetRiskSetRequest
	16, // 12: account.RiskSetService.GetRiskSet:input_type -> account.GetRiskSetRequest
	18, // 13: account.RiskSetService.SubmitAnswers:input_type -> account.SubmitAnswersRequest
	20, // 14: account.BankCardService.GetBankBalance:input_type -> account.GetBankBalanceRequest
	22, // 15: account.BankCardService.BindBankCard:input_type -> account.BindBankCardRequest
	24, // 16: account.BankCardService.UnbindBankCard:input_type -> account.UnbindBankCardRequest
	5,  // 17: account.AccountService.GetCustomInfo:output_type -> account.GetCustomInfoResponse
	9,  // 18: account.AccountService.CreateAccount:output_type -> account.CreateAccountResponse
	11, // 19: account.AccountService.UpdateCustomInfo:output_type -> account.UpdateCustomInfoResponse
	13, // 20: account.AccountService.PullBackCustom:output_type -> account.PullBackCustomResponse
	15, // 21: account.RiskSetService.SetRiskSet:output_type -> account.SetRiskSetResponse
	17, // 22: account.RiskSetService.GetRiskSet:output_type -> account.GetRiskSetResponse
	19, // 23: account.RiskSetService.SubmitAnswers:output_type -> account.SubmitAnswerResponse
	21, // 24: account.BankCardService.GetBankBalance:output_type -> account.GetBankBalanceResponse
	23, // 25: account.BankCardService.BindBankCard:output_type -> account.BindBankCardResponse
	25, // 26: account.BankCardService.UnbindBankCard:output_type -> account.UnbindBankCardResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_account_proto_init() }
func file_protos_account_proto_init() {
	if File_protos_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCustomInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCustomInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullBackCustomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullBackCustomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRiskSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRiskSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRiskSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRiskSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBankBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBankBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindBankCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindBankCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbindBankCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_account_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbindBankCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_account_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_protos_account_proto_goTypes,
		DependencyIndexes: file_protos_account_proto_depIdxs,
		EnumInfos:         file_protos_account_proto_enumTypes,
		MessageInfos:      file_protos_account_proto_msgTypes,
	}.Build()
	File_protos_account_proto = out.File
	file_protos_account_proto_rawDesc = nil
	file_protos_account_proto_goTypes = nil
	file_protos_account_proto_depIdxs = nil
}
